parameters:
    elfinder.form.type.class: Kalamu\CmsAdminBundle\Form\Type\ElfinderType
    app.locales: en|fr

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
           - { name: twig.extension }